CREATE TABLE `site_contacts` (
  `Contact_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Contact_Type` varchar(20) NOT NULL DEFAULT '',
  `Contact_Prefix` varchar(10) DEFAULT NULL,
  `Contact_First_Name` varchar(50) DEFAULT NULL,
  `Contact_Middle_Name` varchar(20) DEFAULT NULL,
  `Contact_Last_Name` varchar(50) DEFAULT NULL,
  `Contact_Suffix` varchar(30) DEFAULT NULL,
  `Contact_Title` varchar(100) DEFAULT NULL,
  `Contact_Address1` varchar(50) DEFAULT NULL,
  `Contact_Address2` varchar(50) DEFAULT NULL,
  `Contact_City` varchar(50) DEFAULT NULL,
  `Contact_State` varchar(5) DEFAULT NULL,
  `Contact_Zip` varchar(20) DEFAULT NULL,
  `Contact_Email_Address` varchar(100) DEFAULT NULL,
  `Contact_Phone1` varchar(20) DEFAULT NULL,
  `Contact_Extension1` varchar(5) DEFAULT NULL,
  `Contact_Phone2` varchar(20) DEFAULT NULL,
  `Contact_Extension2` varchar(5) DEFAULT NULL,
  `Contact_Mobile` varchar(20) DEFAULT NULL,
  `Contact_Fax` varchar(20) DEFAULT NULL,
  `Contact_Is_Primary` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Contact_ID`),
  FULLTEXT KEY `TextSearch` (`Contact_Last_Name`,`Contact_First_Name`,`Contact_Email_Address`,`Contact_City`,`Contact_State`,`Contact_Zip`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
